# Generated by Django 4.1 on 2022-10-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Educational', 'Educational'), ('Fiction', 'Fiction'), ('Journalism', 'Journalism'), ('Religious', 'Religious'), ('History', 'History'), ('Kids', 'Kids'), ('Engineering', 'Engineering'), ('Medcine', 'Medcine')], default='Educational', max_length=15),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('Others', 'Others'), ('Somali', 'Somali'), ('Afan-Oromo', 'Afan-Oromo'), ('Amharic', 'Amharic'), ('Arabic', 'Arabic'), ('English', 'English')], default='English', max_length=15),
        ),
    ]
